### PR TITLE
Adds required classes to pagination template to provide compatibility…

### PR DESCRIPTION
**Pull request by JustinSchneider**
… with Bootstrap 4

### CODE REVIEW

**Comment by adamk33n3r** [comment]
This would be a blessing!

**Comment by adamk33n3r** [comment]
Excited to see this merged! When will this be published to npm?

**Comment by JustinSchneider** [comment]
@mariuszfoltak Any plan to publish this to npm soon?

**Comment by JavaCoder12** [comment]
Eagerly waiting the Bootstrap 4 compatibility for the pagination, could you please let us know  fix available date or tentative date

**Comment by stojankukrika** [comment]
Please publish it on npm to we can use it,it didn't break anything.Please!

**Comment by sirhcybe** [comment]
This would be great. Can we please get an npm push?

**Comment by dreweird** [comment]
I am waiting for the updates lib?? btw, how to run/compile tsconfig.json sorry newb here

**Comment by dreweird** [comment]
i got it....just type npm run build...the pagination works but there's something wrong with the alignment

**Pull request merged**
